version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=quarkus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  postgres_data: