version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quarkus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # persist data even if container shuts down

  monitorMS:
    image: jeanp/rest-api-quarkus:1.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres/quarkus_db
    depends_on:
      - postgres

volumes:
  postgres_data: